# **Análise Exploratória de Dados do TCGA da API GDC**
TCGA: The Cancer Genome Atlas  
GDC: Genomic Data Commons

# Importação de Bibliotecas

In [30]:
import numpy as np
import pandas as pd

# Constantes

In [31]:
# URL HTML base da API GDC
GDC_API_ENDPOINT = 'https://api.gdc.cancer.gov'

# Endpoint para download dos arquivos
DATA_ENDPOINT = f'{GDC_API_ENDPOINT}/data'

# Caminho da pasta de dados externos
EXTERNAL_DATA_PATH = '../../data/external/prototyping'

# Caminho da pasta de dados intermediários
INTERIM_DATA_PATH = '../../data/interim/prototyping'

# Carregamento de Dados

In [32]:
# DataFrame com os casos de interesse
df_cases = pd.read_csv(
    f'{INTERIM_DATA_PATH}/tcga-cases-of-interest.csv'
)

# DataFrame com os arquivos de interesse
df_files = pd.read_csv(
    f'{INTERIM_DATA_PATH}/tcga-files-of-interest.csv'
)

# Cruzamento entre os DataFrames de casos e arquivos
df_eda = df_cases \
    .merge(
        right=df_files,
        left_on='case_id',
        right_on='case_id',
        how='inner'
    )

# 
df_eda['sample_acronym'] = np.where(
    df_eda['tissue_type'] == 'Normal', 'NT', 'TT'
)

df_eda['data_acronym'] = np.where(
    df_eda['data_type'] == 'Gene Expression Quantification', 'mRNA', 'miRNA'
)

df_eda['sample_and_data'] = (
    df_eda['sample_acronym'] + df_eda['data_acronym']
)

In [33]:
df_eda.columns

Index(['case_id', 'case_primary_site', 'case_disease_type', 'project_id',
       'file_id', 'data_format', 'data_type', 'sample_type', 'tissue_type',
       'created_datetime', 'updated_datetime', 'sample_acronym',
       'data_acronym', 'sample_and_data'],
      dtype='object')

# Projetos

In [34]:
# Quantidade de casos e arquivos de interesse por projeto
df_eda \
    .groupby('project_id') \
    .agg(
        case_count=pd.NamedAgg(column='case_id', aggfunc='nunique'),
        file_count=pd.NamedAgg(column='file_id', aggfunc='nunique')
    ) \
    .sort_values(by='case_count', ascending=False)

            case_count  file_count
project_id
TCGA-BRCA         1097        2424
TCGA-UCEC          559        1166
TCGA-KIRC          534        1228
TCGA-HNSC          528        1131
TCGA-LUAD          519        1163
TCGA-THCA          507        1129
TCGA-LUSC          504        1076
TCGA-PRAD          498        1103
TCGA-COAD          459         985
TCGA-STAD          439         939
TCGA-BLCA          412         867
TCGA-LIHC          376         843
TCGA-KIRP          291         647
TCGA-ESCA          185         396
TCGA-PAAD          178         364
TCGA-KICH           66         182
TCGA-CHOL           36          89

In [35]:
# Aumenta o número máximo de linhas no display
pd.set_option('display.max_rows', 500)

# Quantidade de casos e arquivos por tipo de dados em cada projeto
df_eda \
    .groupby(['project_id', 'sample_type', 'data_type']) \
    .agg(
        case_count=pd.NamedAgg(column='case_id', aggfunc='nunique'),
        file_count=pd.NamedAgg(column='file_id', aggfunc='nunique')
    ) \
    .sort_values(by=['project_id', 'sample_type'], ascending=True)

                                                                  case_count  \
project_id sample_type         data_type
TCGA-BLCA  Primary Tumor       Gene Expression Quantification            406
                               Isoform Expression Quantification         409
           Solid Tissue Normal Gene Expression Quantification             19
                               Isoform Expression Quantification          19
TCGA-BRCA  Primary Tumor       Gene Expression Quantification           1095
                               Isoform Expression Quantification        1078
           Solid Tissue Normal Gene Expression Quantification            113
                               Isoform Expression Quantification         104
TCGA-CHOL  Primary Tumor       Gene Expression Quantification             35
                               Isoform Expression Quantification          36
           Solid Tissue Normal Gene Expression Quantification              9
                               Isoform Expression Quantification           9
TCGA-COAD  Primary Tumor       Gene Expression Quantification            458
                               Isoform Expression Quantification         444
           Solid Tissue Normal Gene Expression Quantification             41
                               Isoform Expression Quantification           8
TCGA-ESCA  Primary Tumor       Gene Expression Quantification            184
                               Isoform Expression Quantification         184
           Solid Tissue Normal Gene Expression Quantification             13
                               Isoform Expression Quantification          13
TCGA-HNSC  Primary Tumor       Gene Expression Quantification            520
                               Isoform Expression Quantification         523
           Solid Tissue Normal Gene Expression Quantification             44
                               Isoform Expression Quantification          44
TCGA-KICH  Primary Tumor       Gene Expression Quantification             66
                               Isoform Expression Quantification          66
           Solid Tissue Normal Gene Expression Quantification             25
                               Isoform Expression Quantification          25
TCGA-KIRC  Primary Tumor       Gene Expression Quantification            533
                               Isoform Expression Quantification         516
           Solid Tissue Normal Gene Expression Quantification             72
                               Isoform Expression Quantification          71
TCGA-KIRP  Primary Tumor       Gene Expression Quantification            290
                               Isoform Expression Quantification         291
           Solid Tissue Normal Gene Expression Quantification             32
                               Isoform Expression Quantification          34
TCGA-LIHC  Primary Tumor       Gene Expression Quantification            371
                               Isoform Expression Quantification         372
           Solid Tissue Normal Gene Expression Quantification             50
                               Isoform Expression Quantification          50
TCGA-LUAD  Primary Tumor       Gene Expression Quantification            516
                               Isoform Expression Quantification         513
           Solid Tissue Normal Gene Expression Quantification             59
                               Isoform Expression Quantification          46
TCGA-LUSC  Primary Tumor       Gene Expression Quantification            501
                               Isoform Expression Quantification         478
           Solid Tissue Normal Gene Expression Quantification             51
                               Isoform Expression Quantification          45
TCGA-PAAD  Primary Tumor       Gene Expression Quantification            178
                               Isoform Expression Quantification         178
           Solid Tissue Normal Gene Expression Quantification              4
                               Isoform Expression Quantification           4
TCGA-PRAD  Primary Tumor       Gene Expression Quantification            497
                               Isoform Expression Quantification         494
           Solid Tissue Normal Gene Expression Quantification             52
                               Isoform Expression Quantification          52
TCGA-STAD  Primary Tumor       Gene Expression Quantification            412
                               Isoform Expression Quantification         436
           Solid Tissue Normal Gene Expression Quantification             36
                               Isoform Expression Quantification          41
TCGA-THCA  Primary Tumor       Gene Expression Quantification            505
                               Isoform Expression Quantification         506
           Solid Tissue Normal Gene Expression Quantification             59
                               Isoform Expression Quantification          59
TCGA-UCEC  Primary Tumor       Gene Expression Quantification            545
                               Isoform Expression Quantification         538
           Solid Tissue Normal Gene Expression Quantification             35
                               Isoform Expression Quantification          33

                                                                  file_count
project_id sample_type         data_type
TCGA-BLCA  Primary Tumor       Gene Expression Quantification            412
                               Isoform Expression Quantification         417
           Solid Tissue Normal Gene Expression Quantification             19
                               Isoform Expression Quantification          19
TCGA-BRCA  Primary Tumor       Gene Expression Quantification           1111
                               Isoform Expression Quantification        1096
           Solid Tissue Normal Gene Expression Quantification            113
                               Isoform Expression Quantification         104
TCGA-CHOL  Primary Tumor       Gene Expression Quantification             35
                               Isoform Expression Quantification          36
           Solid Tissue Normal Gene Expression Quantification              9
                               Isoform Expression Quantification           9
TCGA-COAD  Primary Tumor       Gene Expression Quantification            481
                               Isoform Expression Quantification         455
           Solid Tissue Normal Gene Expression Quantification             41
                               Isoform Expression Quantification           8
TCGA-ESCA  Primary Tumor       Gene Expression Quantification            184
                               Isoform Expression Quantification         186
           Solid Tissue Normal Gene Expression Quantification             13
                               Isoform Expression Quantification          13
TCGA-HNSC  Primary Tumor       Gene Expression Quantification            520
                               Isoform Expression Quantification         523
           Solid Tissue Normal Gene Expression Quantification             44
                               Isoform Expression Quantification          44
TCGA-KICH  Primary Tumor       Gene Expression Quantification             66
                               Isoform Expression Quantification          66
           Solid Tissue Normal Gene Expression Quantification             25
                               Isoform Expression Quantification          25
TCGA-KIRC  Primary Tumor       Gene Expression Quantification            541
                               Isoform Expression Quantification         544
           Solid Tissue Normal Gene Expression Quantification             72
                               Isoform Expression Quantification          71
TCGA-KIRP  Primary Tumor       Gene Expression Quantification            290
                               Isoform Expression Quantification         291
           Solid Tissue Normal Gene Expression Quantification             32
                               Isoform Expression Quantification          34
TCGA-LIHC  Primary Tumor       Gene Expression Quantification            371
                               Isoform Expression Quantification         372
           Solid Tissue Normal Gene Expression Quantification             50
                               Isoform Expression Quantification          50
TCGA-LUAD  Primary Tumor       Gene Expression Quantification            539
                               Isoform Expression Quantification         519
           Solid Tissue Normal Gene Expression Quantification             59
                               Isoform Expression Quantification          46
TCGA-LUSC  Primary Tumor       Gene Expression Quantification            502
                               Isoform Expression Quantification         478
           Solid Tissue Normal Gene Expression Quantification             51
                               Isoform Expression Quantification          45
TCGA-PAAD  Primary Tumor       Gene Expression Quantification            178
                               Isoform Expression Quantification         178
           Solid Tissue Normal Gene Expression Quantification              4
                               Isoform Expression Quantification           4
TCGA-PRAD  Primary Tumor       Gene Expression Quantification            501
                               Isoform Expression Quantification         498
           Solid Tissue Normal Gene Expression Quantification             52
                               Isoform Expression Quantification          52
TCGA-STAD  Primary Tumor       Gene Expression Quantification            412
                               Isoform Expression Quantification         446
           Solid Tissue Normal Gene Expression Quantification             36
                               Isoform Expression Quantification          45
TCGA-THCA  Primary Tumor       Gene Expression Quantification            505
                               Isoform Expression Quantification         506
           Solid Tissue Normal Gene Expression Quantification             59
                               Isoform Expression Quantification          59
TCGA-UCEC  Primary Tumor       Gene Expression Quantification            553
                               Isoform Expression Quantification         545
           Solid Tissue Normal Gene Expression Quantification             35
                               Isoform Expression Quantification          33

In [69]:
df_eda.value_counts(['project_id', 'sample_type', 'data_type'])

project_id  sample_type          data_type
TCGA-BRCA   Primary Tumor        Gene Expression Quantification       1111
                                 Isoform Expression Quantification    1096
TCGA-UCEC   Primary Tumor        Gene Expression Quantification        553
                                 Isoform Expression Quantification     545
TCGA-KIRC   Primary Tumor        Isoform Expression Quantification     544
                                 Gene Expression Quantification        541
TCGA-LUAD   Primary Tumor        Gene Expression Quantification        539
TCGA-HNSC   Primary Tumor        Isoform Expression Quantification     523
                                 Gene Expression Quantification        520
TCGA-LUAD   Primary Tumor        Isoform Expression Quantification     519
TCGA-THCA   Primary Tumor        Isoform Expression Quantification     506
                                 Gene Expression Quantification        505
TCGA-LUSC   Primary Tumor        Gene Expression Quantification        502
TCGA-PRAD   Primary Tumor        Gene Expression Quantification        501
                                 Isoform Expression Quantification     498
TCGA-COAD   Primary Tumor        Gene Expression Quantification        481
TCGA-LUSC   Primary Tumor        Isoform Expression Quantification     478
TCGA-COAD   Primary Tumor        Isoform Expression Quantification     455
TCGA-STAD   Primary Tumor        Isoform Expression Quantification     446
TCGA-BLCA   Primary Tumor        Isoform Expression Quantification     417
                                 Gene Expression Quantification        412
TCGA-STAD   Primary Tumor        Gene Expression Quantification        412
TCGA-LIHC   Primary Tumor        Isoform Expression Quantification     372
                                 Gene Expression Quantification        371
TCGA-KIRP   Primary Tumor        Isoform Expression Quantification     291
                                 Gene Expression Quantification        290
TCGA-ESCA   Primary Tumor        Isoform Expression Quantification     186
                                 Gene Expression Quantification        184
TCGA-PAAD   Primary Tumor        Gene Expression Quantification        178
                                 Isoform Expression Quantification     178
TCGA-BRCA   Solid Tissue Normal  Gene Expression Quantification        113
                                 Isoform Expression Quantification     104
TCGA-KIRC   Solid Tissue Normal  Gene Expression Quantification         72
                                 Isoform Expression Quantification      71
TCGA-KICH   Primary Tumor        Gene Expression Quantification         66
                                 Isoform Expression Quantification      66
TCGA-THCA   Solid Tissue Normal  Gene Expression Quantification         59
TCGA-LUAD   Solid Tissue Normal  Gene Expression Quantification         59
TCGA-THCA   Solid Tissue Normal  Isoform Expression Quantification      59
TCGA-PRAD   Solid Tissue Normal  Gene Expression Quantification         52
                                 Isoform Expression Quantification      52
TCGA-LUSC   Solid Tissue Normal  Gene Expression Quantification         51
TCGA-LIHC   Solid Tissue Normal  Isoform Expression Quantification      50
                                 Gene Expression Quantification         50
TCGA-LUAD   Solid Tissue Normal  Isoform Expression Quantification      46
TCGA-STAD   Solid Tissue Normal  Isoform Expression Quantification      45
TCGA-LUSC   Solid Tissue Normal  Isoform Expression Quantification      45
TCGA-HNSC   Solid Tissue Normal  Isoform Expression Quantification      44
                                 Gene Expression Quantification         44
TCGA-COAD   Solid Tissue Normal  Gene Expression Quantification         41
TCGA-CHOL   Primary Tumor        Isoform Expression Quantification      36
TCGA-STAD   Solid Tissue Normal  Gene Expression Quantification         36
TCGA-CHOL   Primary Tumor        Gene Expression Quantification         35
TCGA-UCEC   Solid Tissue Normal  Gene Expression Quantification         35
TCGA-KIRP   Solid Tissue Normal  Isoform Expression Quantification      34
TCGA-UCEC   Solid Tissue Normal  Isoform Expression Quantification      33
TCGA-KIRP   Solid Tissue Normal  Gene Expression Quantification         32
TCGA-KICH   Solid Tissue Normal  Isoform Expression Quantification      25
                                 Gene Expression Quantification         25
TCGA-BLCA   Solid Tissue Normal  Isoform Expression Quantification      19
                                 Gene Expression Quantification         19
TCGA-ESCA   Solid Tissue Normal  Isoform Expression Quantification      13
                                 Gene Expression Quantification         13
TCGA-CHOL   Solid Tissue Normal  Isoform Expression Quantification       9
                                 Gene Expression Quantification          9
TCGA-COAD   Solid Tissue Normal  Isoform Expression Quantification       8
TCGA-PAAD   Solid Tissue Normal  Isoform Expression Quantification       4
                                 Gene Expression Quantification          4
dtype: int64

# Casos

In [51]:
df_test = df_eda[['case_id', 'file_id', 'sample_and_data']].copy()

df_test['TTmRNA'] = np.where(df_test['sample_and_data'] == 'TTmRNA', 1, 0)
df_test['TTmiRNA'] = np.where(df_test['sample_and_data'] == 'TTmiRNA', 1, 0)
df_test['NTmRNA'] = np.where(df_test['sample_and_data'] == 'NTmRNA', 1, 0)
df_test['NTmiRNA'] = np.where(df_test['sample_and_data'] == 'NTmiRNA', 1, 0)

df_test['file_count'] = (
    df_test['TTmRNA'] + df_test['TTmiRNA'] + df_test['NTmRNA'] + df_test['NTmiRNA']
)

# Quantidade de arquivos de interesse por caso
df = df_test \
    .groupby('case_id') \
    .agg(
        file_count=pd.NamedAgg(column='file_count', aggfunc='sum'),
        TTmRNA_count=pd.NamedAgg(column='TTmRNA', aggfunc='sum'),
        TTmiRNA_count=pd.NamedAgg(column='TTmiRNA', aggfunc='sum'),
        NTmRNA_count=pd.NamedAgg(column='NTmRNA', aggfunc='sum'),
        NTmiRNA_count=pd.NamedAgg(column='NTmiRNA', aggfunc='sum')
    ) \
    .sort_values(
        by=['file_count', 'TTmRNA_count', 'TTmiRNA_count', 'NTmRNA_count', 'NTmiRNA_count'],
        ascending=False
    )

df

,file_count,TTmRNA_count,TTmiRNA_count,NTmRNA_count,NTmiRNA_count
case_id,,,,,
556fcbc8-172a-4af1-8822-ae036e8d68e8,8,3,3,1,1
8c7e74e0-71ef-49b8-9217-94b8ef740ef9,8,3,3,1,1
f130f376-5801-40f9-975d-a7e2f7b5670d,8,3,3,1,1
0c0b610e-fe4c-406d-a5ed-5cc3b11dabf5,7,3,3,1,0
889aec8e-14ba-48d9-8fe1-f2416e82b333,7,3,3,1,0
...,...,...,...,...,...
ed46cc12-2edd-4c95-9814-54b5b6682fcd,1,0,1,0,0
f383df81-a334-43c6-a5be-ea00013a4f6a,1,0,1,0,0
f61d599a-43bd-4743-9568-678317e75955,1,0,1,0,0
f9cf605f-f287-4eba-8e8f-8ba47e14ecc4,1,0,1,0,0
42ebfec9-6e28-4d72-9b9f-23a836800921,1,0,0,1,0

In [67]:
count_abs = df.value_counts(ascending=False)
count_norm = df.value_counts(normalize=True, ascending=False)

df_counts = pd.DataFrame({
    'count': count_abs,
    'count%': round(count_norm * 100, 2)
})

df_counts = df_counts.reset_index()
df_counts

,file_count,TTmRNA_count,TTmiRNA_count,NTmRNA_count,NTmiRNA_count,count,count%
0,2,1,1,0,0,6199,86.24
1,4,1,1,1,1,584,8.12
2,1,1,0,0,0,108,1.50
3,3,1,1,1,0,89,1.24
4,1,0,1,0,0,55,0.77
5,3,1,1,0,1,38,0.53
6,3,1,2,0,0,33,0.46
7,6,3,3,0,0,17,0.24
8,2,0,0,1,1,11,0.15
9,4,3,1,0,0,8,0.11
10,4,2,2,0,0,8,0.11
11,3,0,1,1,1,6,0.08
12,3,1,0,1,1,4,0.06
13,6,2,2,1,1,4,0.06
14,6,3,1,1,1,3,0.04
15,8,3,3,1,1,3,0.04
16,2,0,2,0,0,3,0.04
17,5,3,1,1,0,3,0.04
18,4,1,1,0,2,2,0.03
19,7,3,3,1,0,2,0.03
20,5,1,1,1,2,2,0.03
21,1,0,0,1,0,1,0.01
22,5,3,2,0,0,1,0.01
23,5,2,2,1,0,1,0.01
24,2,2,0,0,0,1,0.01
25,2,1,0,1,0,1,0.01
26,3,2,1,0,0,1,0.01